.Dd June 15, 2026
.Dt LIBSIGSCAN 3
.Os
.Sh NAME
.Nm libsigscan.h
.Nd Library for binary signature scanning
.Sh SYNOPSIS
.In libsigscan.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libsigscan_get_version
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_get_access_flags_read
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_get_codepage
.Fa "int *codepage"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_set_codepage
.Fa "int codepage"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libsigscan_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_notify_set_stream
.Fa "FILE *stream"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_notify_stream_open
.Fa "const char *filename"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_notify_stream_close
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libsigscan_error_free
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_error_fprint
.Fa "libsigscan_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_error_sprint
.Fa "libsigscan_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_error_backtrace_fprint
.Fa "libsigscan_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_error_backtrace_sprint
.Fa "libsigscan_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
Scanner functions
.nf
.Ft int
.Fo libsigscan_scanner_initialize
.Fa "libsigscan_scanner_t **scanner"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_free
.Fa "libsigscan_scanner_t **scanner"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_signal_abort
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_set_scan_buffer_size
.Fa "libsigscan_scanner_t *scanner"
.Fa "size_t scan_buffer_size"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_add_signature
.Fa "libsigscan_scanner_t *scanner"
.Fa "const char *identifier"
.Fa "size_t identifier_length"
.Fa "off64_t pattern_offset"
.Fa "const uint8_t *pattern"
.Fa "size_t pattern_size"
.Fa "uint32_t signature_flags"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_scan_start
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_scan_stop
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_scan_buffer
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "const uint8_t *buffer"
.Fa "size_t buffer_size"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_scan_file
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "const char *filename"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scanner_scan_file_wide
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "const wchar_t *filename"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libsigscan_scanner_scan_file_io_handle
.Fa "libsigscan_scanner_t *scanner"
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Pp
Scan state functions
.nf
.Ft int
.Fo libsigscan_scan_state_initialize
.Fa "libsigscan_scan_state_t **scan_state"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_state_free
.Fa "libsigscan_scan_state_t **scan_state"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_state_set_data_size
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "size64_t data_size"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_state_get_number_of_results
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "int *number_of_results"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_state_get_result
.Fa "libsigscan_scan_state_t *scan_state"
.Fa "int result_index"
.Fa "libsigscan_scan_result_t **scan_result"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Pp
Scan result functions
.nf
.Ft int
.Fo libsigscan_scan_result_free
.Fa "libsigscan_scan_result_t **scan_result"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_result_get_identifier_size
.Fa "libsigscan_scan_result_t *scan_result"
.Fa "size_t *identifier_size"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libsigscan_scan_result_get_identifier
.Fa "libsigscan_scan_result_t *scan_result"
.Fa "char *identifier"
.Fa "size_t identifier_size"
.Fa "libsigscan_error_t **error"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libsigscan_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libsigscan.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh SEE ALSO
.In libsigscan.h
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libsigscan/issues
.Sh COPYRIGHT
Copyright (C) 2014-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
