.Dd June 27, 2026
.Dt SIGSCAN 1
.Os
.Sh NAME
.Nm sigscan
.Nd scans a file for binary signatures
.Sh SYNOPSIS
.Nm sigscan
.Op Fl c Ar path
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm sigscan
is a utility to scan a file for binary signatures
.Pp
.Nm sigscan
is part of the
.Nm libsigscan
package.
.Nm libsigscan
is a library to scan a file for binary signatures
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar path
specify the configuration file, defaults to: sigscan.conf
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# sigscan -c sigscan.conf qcow.bin
sigscan 20260627
.sp
Signature scanner:
	Number of scan results	: 1
.sp
Scan result: 1
	Identifier		: qcow
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libsigscan/issues
.Sh COPYRIGHT
Copyright (C) 2014-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
